#!/usr/bin/env bash
# ******************************************************
# Author       : kaleo
# Last modified: 2017-05-15 19:33
# Email        : kaleo1990@hotmail.com
# Filename     : dbback
# Description  : 
# ******************************************************
mysqldump -uroot -pkaleozhou ordersys > ordersys.sql
